### ISSUE TITLE
AuthenticationError in 'send' handler

### ISSUE THREAD

**Issue by Jaewook-Lee** [kookmin-sw/capstone-2023-05#90]
master 브랜치의 내용에 대해 배포 테스트를 진행하는 중 _send_ handler에서 아래의 에러를 얻었습니다.  
> [ERROR] AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
Traceback (most recent call last):
  File "/var/task/src/utility/websocket.py", line 37, in wrapper
    return func(event, context, wsclient)
  File "/var/task/src/lambda/handler.py", line 111, in send_handler
    return app.send_handler(event, context, wsclient)
  File "/var/task/src/game/app.py", line 178, in send_handler
    if filter_opinion(opinion) == 1:
  File "/var/task/src/game/app.py", line 1183, in filter_opinion
    response = openai.ChatCompletion.create(
  File "/var/task/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/var/task/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/var/task/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/var/task/openai/api_requestor.py", line 134, in __init__
    self.api_key = key or util.default_api_key()
  File "/var/task/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(

이 사항은 @Binsk-dev 가 확인해봤으면 합니다.

**Comment by Binsk-dev** [comment]
## 조치사항 안내
### 1. AWS Systems Manager Parameter Store에 API 키 저장하기
### 2. serverless.yml 수정하기
```yaml
service: my-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  my-function:
    handler: handler.my_function
    environment:
      API_KEY: ${ssm:/my-ssm-parameter-name}
```
### 3. API_KEY 소스코드에 반영
```python
import os
import openai

api_key = os.environ.get('API_KEY')
openai.api_key = api_key
```
### 4. serverless를 이용한 배포
```zsh
sls deploy
```
